export const slugsNomeOficial = {
  "afeganistao": "Afeganistão",
  "africa-do-sul": "África do Sul",
  "albania": "Albânia",
  "alemanha": "Alemanha",
  "angola": "Angola",
  "anguilla": "Anguilla",
  "antigua-e-barbuda": "Antígua e Barbuda",
  "argentina": "Argentina",
  "argelia": "Argélia",
  "armenia": "Armênia",
  "aruba": "Aruba",
  "arabia-saudita": "Arábia Saudita",
  "australia": "Austrália",
  "austria": "Áustria",
  "azerbaijao": "Azerbaijão",
  "bahamas": "Bahamas",
  "bahrein": "Bahrein",
  "bangladesh": "Bangladesh",
  "barbados": "Barbados",
  "belarus": "Bielorrússia",
  "belize": "Belize",
  "benin": "Benim",
  "bermudas": "Bermudas",
  "bolivia": "Bolívia",
  "bonaire": "Bonaire",
  "botsuana": "Botsuana",
  "brasil": "Brasil",
  "brunei": "Brunei",
  "bulgaria": "Bulgária",
  "burkina-faso": "Burkina Faso",
  "burundi": "Burundi",
  "butao": "Butão",
  "belgica": "Bélgica",
  "bosnia-e-herzegovina": "Bósnia e Herzegovina",
  "cabo-verde": "Cabo Verde",
  "camaeroes": "Camarões",
  "camboja": "Camboja",
  "canada": "Canadá",
  "catar": "Catar",
  "cazaquistao": "Cazaquistão",
  "chade": "Chade",
  "chile": "Chile",
  "china": "China",
  "chipre": "Chipre",
  "colombia": "Colômbia",
  "comores": "Comores",
  "coreia-do-sul": "Coreia do Sul",
  "coreia-do-norte": "Coreia do Norte",
  "costa-rica": "Costa Rica",
  "costa-do-marfim": "Costa do Marfim",
  "croacia": "Croácia",
  "cuba": "Cuba",
  "curacao": "Curaçao",
  "dinamarca": "Dinamarca",
  "djibouti": "Djibuti",
  "dominica": "Dominica",
  "egito": "Egito",
  "el-salvador": "El Salvador",
  "emirados-arabes-unidos": "Emirados Árabes Unidos",
  "equador": "Equador",
  "eritreia": "Eritreia",
  "eslovacia": "Eslováquia",
  "eslovenia": "Eslovênia",
  "espanha": "Espanha",
  "essuatini": "Essuatíni",
  "estados-federados-da-micronesia": "Estados Federados da Micronésia",
  "estados-unidos": "Estados Unidos",
  "estonia": "Estônia",
  "etiopia": "Etiópia",
  "fiji": "Fiji",
  "filipinas": "Filipinas",
  "finlandia": "Finlândia",
  "franca": "França",
  "gabao": "Gabão",
  "gana": "Gana",
  "georgia": "Geórgia",
  "granada": "Granada",
  "groelandia": "Groenlândia",
  "grecia": "Grécia",
  "guadalupe": "Guadalupe",
  "guam": "Guam",
  "guatemala": "Guatemala",
  "guiana": "Guiana",
  "guiana-francesa": "Guiana Francesa",
  "guine": "Guiné",
  "guine-equatorial": "Guiné Equatorial",
  "guine-bissau": "Guiné-Bissau",
  "gambia": "Gâmbia",
  "haiti": "Haiti",
  "honduras": "Honduras",
  "hungria": "Hungria",
  "ilha-de-sao-martinho": "Ilha de São Martinho",
  "ilhas-canarias": "Ilhas Canárias",
  "ilhas-cayman": "Ilhas Cayman",
  "ilhas-faroe": "Ilhas Faroé",
  "ilhas-malvinas": "Ilhas Malvinas",
  "ilhas-marianas-do-norte": "Ilhas Marianas do Norte",
  "ilhas-marshall": "Ilhas Marshall",
  "ilhas-mauricio": "Ilhas Maurício",
  "ilhas-salomao": "Ilhas Salomão",
  "ilhas-virgens-americanas": "Ilhas Virgens Americanas",
  "ilhas-virgens-britanicas": "Ilhas Virgens Britânicas",
  "indonesia": "Indonésia",
  "india": "Índia",
  "iraque": "Iraque",
  "irlanda": "Irlanda",
  "ira": "Irã",
  "islandia": "Islândia",
  "israel": "Israel",
  "italia": "Itália",
  "iemen": "Iémen",
  "jamaica": "Jamaica",
  "japao": "Japão",
  "jordania": "Jordânia",
  "kosovo": "Kosovo",
  "kuwait": "Kuwait",
  "laos": "Laos",
  "lesoto": "Lesoto",
  "letonia": "Letônia",
  "liberia": "Libéria",
  "lituania": "Lituânia",
  "luxemburgo": "Luxemburgo",
  "libano": "Líbano",
  "libia": "Líbia",
  "macedonia": "Macedônia do Norte",
  "madagascar": "Madagáscar",
  "malawi": "Malawi",
  "maldivas": "Maldivas",
  "mali": "Mali",
  "malta": "Malta",
  "malasia": "Malásia",
  "marrocos": "Marrocos",
  "martinica": "Martinica",
  "mauritania": "Mauritânia",
  "mayotte": "Mayotte",
  "moldavia": "Moldávia",
  "mongolia": "Mongólia",
  "montenegro": "Montenegro",
  "montserrat": "Montserrat",
  "mocambique": "Moçambique",
  "myanmar": "Myanmar",
  "mexico": "México",
  "namibia": "Namíbia",
  "nauru": "Nauru",
  "nepal": "Nepal",
  "nicaragua": "Nicarágua",
  "nigeria": "Nigéria",
  "noruega": "Noruega",
  "nova-caledonia": "Nova Caledônia",
  "nova-zelandia": "Nova Zelândia",
  "niger": "Níger",
  "oma": "Omã",
  "palau": "Palau",
  "palestina": "Palestina",
  "panama": "Panamá",
  "papua-nova-guine": "Papua-Nova Guiné",
  "paquistao": "Paquistão",
  "paraguai": "Paraguai",
  "paises-baixos": "Países Baixos",
  "peru": "Peru",
  "polinesia-francesa": "Polinésia Francesa",
  "polonia": "Polônia",
  "porto-rico": "Porto Rico",
  "portugal": "Portugal",
  "quirguistao": "Quirguistão",
  "quenia": "Quênia",
  "reino-unido": "Reino Unido",
  "republica-centro-africana": "República Centro-Africana",
  "republica-democratica-do-congo": "República Democrática do Congo",
  "republica-dominicana": "República Dominicana",
  "republica-tcheca": "República Tcheca",
  "republica-do-congo": "República do Congo",
  "romenia": "Romênia",
  "ruanda": "Ruanda",
  "reunion": "Reunião",
  "russia": "Rússia",
  "saara-ocidental": "Saara Ocidental",
  "saba": "Saba",
  "samoa-americana": "Samoa Americana",
  "santa-lucia": "Santa Lúcia",
  "santo-eustaquio": "Santo Eustáquio",
  "senegal": "Senegal",
  "serra-leoa": "Serra Leoa",
  "seicheles": "Seicheles",
  "somalia": "Somália",
  "sri-lanka": "Sri Lanka",
  "sudao": "Sudão",
  "sudao-do-sul": "Sudão do Sul",
  "suriname": "Suriname",
  "suecia": "Suécia",
  "suica": "Suíça",
  "sao-bartolomeu": "São Bartolomeu",
  "sao-cristovao-e-nevis": "São Cristóvão e Névis",
  "sao-martinho": "São Martinho",
  "sao-tome-e-principe": "São Tomé e Príncipe",
  "sao-vicente-e-granadinas": "São Vicente e Granadinas",
  "servia": "Sérvia",
  "siria": "Síria",
  "tailandia": "Tailândia",
  "taiwan": "Taiwan",
  "tajiquistao": "Tajiquistão",
  "tanzania": "Tanzânia",
  "timor-leste": "Timor-Leste",
  "togo": "Togo",
  "tonga": "Tonga",
  "trindade-e-tobago": "Trindade e Tobago",
  "tunisia": "Tunísia",
  "turcomenistao": "Turcomenistão",
  "ilhas-turcas-e-caicos": "Ilhas Turcas e Caicos",
  "turquia": "Turquia",
  "tuvalu": "Tuvalu",
  "ucrania": "Ucrânia",
  "uganda": "Uganda",
  "uruguai": "Uruguai",
  "uzbequistao": "Uzbequistão",
  "vanuatu": "Vanuatu",
  "venezuela": "Venezuela",
  "vietna": "Vietnã",
  "zimbabue": "Zimbábue",
  "zambia": "Zâmbia"
};